# Generated by Django 4.2.1 on 2024-02-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PRODUCT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('PRODUCT_NAME', models.CharField(max_length=100)),
                ('PRODUCT_CATEGORY', models.CharField(max_length=100)),
                ('COST_PRICE', models.DecimalField(decimal_places=2, max_digits=8)),
                ('SELLING_PRICE', models.DecimalField(decimal_places=2, max_digits=8)),
                ('SALES_DATA', models.IntegerField()),
                ('QUANTITY_SOLD', models.IntegerField()),
                ('SEASON', models.CharField(max_length=20)),
                ('PROFIT_MARGIN', models.CharField(max_length=10)),
                ('RATING', models.DecimalField(decimal_places=1, max_digits=3)),
                ('SPACE_OCCUPIED', models.IntegerField()),
                ('NO_OF_DAYS_LEFT', models.IntegerField()),
            ],
        ),
    ]
